spring:
  application:
    name: 'security_project1'

  h2:
    console:
      enabled: 'true'

server:
  port: 8080
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-alias: 'springboot'
    key-store-password: '     '
    key-store: classpath:keystore.p12


